# Makefile to export Alembic environment variables

export ALEMBIC_USERNAME=postgres
export ALEMBIC_PASSWORD=postgres
export DATABASE_NAME=postgres

.PHONY: export
export:
	@echo "Environment variables exported."
